language: python

matrix:
  include:
  - python: 3.3
    dist: trusty
  - python: 3.4
    dist: trusty
  - python: 3.5
    dist: xenial
  - python: 3.6
    dist: xenial
  - python: 3.7
    dist: xenial

addons:
  apt:
    packages:
    - gtk+3.0
    - python3-gi

install:
  - pip install -r requirements.txt
  - pip install pycodestyle

script:
  - make lint
