# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python3-gi gtk+3.0

install:
  - pip install -r requirements.txt
  - pip install pep8

script:
  - make lint
